### ISSUE TITLE
Proper shift register

### ISSUE THREAD

**Issue by jordens** [quartiq/Phaser_STFT_Pulsegen#2]
https://github.com/quartiq/Phaser_STFT_Pulsegen/blob/8ef1efcc9172f8691eb0176f6c8bc05b56473af8/phaser_stft.py#L23

There is no shifting here 
Inp needs to be the lsb or you have to discard the lsb..

**Comment by nkrackow** [comment]
haha yeah thats where I got annoyed at MSB/LSB in migen yesterdy, I just didn't push the changes.

**Comment by jordens** [comment]
Ok!
